### ISSUE TITLE
what is this error?

### ISSUE THREAD

**Issue by navidrct** [NordicSemiconductor/Android-DFU-Library#26]
# 25 i fix this problem by sending contex of my app .

now i have this problem that cam from DFU Lib

```
10-24 15:00:30.442 13364-13656/com.asidesigner.smartlamp E/DfuBaseService: An exception occurred while calculating file size
                                                                           java.io.IOException: The ZIP file must contain an Application, a Soft Device and/or a Bootloader.
                                                                               at no.nordicsemi.android.dfu.internal.ArchiveInputStream.<init>(ArchiveInputStream.java:245)
                                                                               at no.nordicsemi.android.dfu.DfuBaseService.openInputStream(DfuBaseService.java:1148)
                                                                               at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:877)
                                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                               at android.os.Looper.loop(Looper.java:193)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
```

it suppose to work with hex file in sdk v6 then i put hex file in program to work with

**Comment by philips77** [comment]
Yes, then you have to use setHexOrBin method, not setZip.
