### ISSUE TITLE
Android 7 DFU update cannot be performed

### ISSUE THREAD

**Issue by alphaYuto** [NordicSemiconductor/Android-DFU-Library#271]
**DFU Bootloader version (please complete the following information):**
 - SDK version: 
 - Bonding used: no
 - Library version: 1.9.1

**Device information (please complete the following information):**
 - Device:
 - OS: Android7

**Your question**
Hello
I implemented a DFU update on Android 7.0, but I couldn't run DFU and got an error. The content of the error is "java.lang.NoClassDefFoundError: Failed resolution of: Landroid / app / Notification Channel". Is there a solution?
Attach the log.

**Logs**
```
FATAL EXCEPTION: main
Process: com.example.InspectionApp, PID: 4175
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
 	at no.nordicsemi.android.dfu.DfuServiceInitiator.createDfuNotificationChannel(DfuServiceInitiator.java:887)
 	at com.example.insolemodulefm_inspectionapp.DfuFragment.sentDfuZipFile(DfuFragment.java:271)
 	at com.example.insolemodulefm_inspectionapp.DfuFragment$2.onClick(DfuFragment.java:166)
```
[error_log_20200909.txt](https://github.com/NordicSemiconductor/Android-DFU-Library/files/5199231/error_log_20200909.txt)

**Comment by philips77** [comment]
You need to set the notification channels on Android 8 or newer only.

**Comment by alphaYuto** [comment]
In Android 8 and earlier, the process of setting up a notification channel is not described.
Unless you explain the process of disabling the notification channel setting
Is the notification channel set automatically?

**Comment by philips77** [comment]
Notification Channels were added in Android 8: https://developer.android.com/training/notify-user/channels
For older platforms you just don't call this method and everything should work.
Also, in your code, you set the channels for 8+, but also disable notifications, so channels are not needed, but you keep them enabled for pre-8.

**Comment by roshanrajaratnam** [comment]
Closing due to inactivity. Please feel free to re-open if the issue persists.
