### ISSUE TITLE
DfuBaseService: An exception occurred while opening files. Did you set the firmware file?

### ISSUE THREAD

**Issue by 979451341** [NordicSemiconductor/Android-DFU-Library#301]
```
DfuBaseService: An exception occurred while opening files. Did you set the firmware file?
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.available()' on a null object reference
        at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1062)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by philips77** [comment]
So, as the message suggests, did you call any of those methods before starting DFU:
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/b5d587bfbfaa5b1eacebce3a8846746a9d3a9793/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceInitiator.java#L611-L732
