### ISSUE TITLE
We are seeing bootloader file null not found error while updating the firmware

### ISSUE THREAD

**Issue by sandeephattiholi** [NordicSemiconductor/Android-DFU-Library#310]
**DFU Bootloader version (please complete the following information):**
 - SDK version: [e.g. SDK 26]
 - Bonding used: [yes]
 - Library version: [e.g. 1.8.1]

**Device information (please complete the following information):**
 - OS: [e.g. Android 8.1]

**Describe the bug**
While update the bootloader and firmware through DFU library on Android8.1 we are seeing 
DfuBaseService: java.io.IOException: Bootloader file null not found.

**Logs**
```
01-01 00:31:29.398  2083  3678 E DfuBaseService: An exception occurred while calculating file size
01-01 00:31:29.398  2083  3678 E DfuBaseService: java.io.IOException: Bootloader file null not found.
01-01 00:31:29.398  2083  3678 E DfuBaseService: 	at no.nordicsemi.android.dfu.internal.ArchiveInputStream.<init>(:159)
01-01 00:31:29.398  2083  3678 E DfuBaseService: 	at no.nordicsemi.android.dfu.DfuBaseService.openInputStream(:1287)
01-01 00:31:29.398  2083  3678 E DfuBaseService: 	at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(:1042)
01-01 00:31:29.398  2083  3678 E DfuBaseService: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
01-01 00:31:29.398  2083  3678 E DfuBaseService: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 00:31:29.398  2083  3678 E DfuBaseService: 	at android.os.Looper.loop(Looper.java:164)
01-01 00:31:29.398  2083  3678 E DfuBaseService: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by philips77** [comment]
Sorry for the late response, but as the error message indicated, the ZIP file must have been invalid (bin file for the bootloader update missing).
