### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by marcbaldwin** [NordicSemiconductor/Android-DFU-Library#312]
**DFU Bootloader version (please complete the following information):**
 - SDK version: [e.g. SDK 16]
 - Bonding used: [yes]
 - Library version: [e.g. 1.9.1]

**Device information (please complete the following information):**
 - Device: Any device running Android 12
 - OS: Android 12

**Describe the bug**
App crashes when trying to perform a DFU

**Logs**
```
java.lang.IllegalArgumentException: co.beeline.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at no.nordicsemi.android.dfu.DfuBaseService.startForeground(DfuBaseService.java:1862)
        at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1142)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by marcbaldwin** [comment]
@philips77 apologies for the direct tag. Is this repository still maintained?

**Comment by marcbaldwin** [comment]
Great, I've forked the library and am working on adding Android12 support. Will create a PR in due course.
