### ISSUE TITLE
.zip fails on Android 12

### ISSUE THREAD

**Issue by MikeInMinnesota** [NordicSemiconductor/Android-DFU-Library#327]
**DFU Bootloader version (please complete the following information):**
 - SDK version: [e.g. SDK 16]  15.3
 - Bonding used: [yes/no]  no
 - Library version: [e.g. 1.9.1] 1.10.4

**Device information (please complete the following information):**
 - Device: [e.g. Samsung S10]  Pixel 3XL
 - OS: [e.g. Android 9] Android 12

**Describe the bug**
Illegal operation due to not having file Uri.

A .zip was selected as the update source and an exception occurs.  It looks like the problem is that the Uri was a "context" type instead of a "file" type resource.  This appears to be a change from Android 11 to Android 12.

**Logs**
```
E/DFU_FILE_MANAGER: Error during creation file from uri.
    java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://com.android.providers.downloads.documents/document/msf%3A2019
        at androidx.core.net.UriKt.toFile(Uri.kt:43)
        at no.nordicsemi.dfu.profile.main.data.DFUFileManager.createFromFile(DFUFileManager.kt:33)
        at no.nordicsemi.dfu.profile.main.data.DFUFileManager.createFile(DFUFileManager.kt:20)
        at no.nordicsemi.dfu.profile.main.repository.DFURepository.setZipFile(DFURepository.kt:29)
        at no.nordicsemi.dfu.profile.main.viewmodel.DFUViewModel.onZipFileSelected(DFUViewModel.kt:146)
        at no.nordicsemi.dfu.profile.main.viewmodel.DFUViewModel.onEvent(DFUViewModel.kt:132)
        at no.nordicsemi.dfu.profile.main.view.DFUScreenKt$DFUScreen$onEvent$1.invoke(DFUScreen.kt:28)
        at no.nordicsemi.dfu.profile.main.view.DFUScreenKt$DFUScreen$onEvent$1.invoke(DFUScreen.kt:28)
        at no.nordicsemi.dfu.profile.main.view.DFUSelectFileViewKt$DFUNotSelectedFileView$launcher$1$1.invoke(DFUSelectFileView.kt:48)
        at no.nordicsemi.dfu.profile.main.view.DFUSelectFileViewKt$DFUNotSelectedFileView$launcher$1$1.invoke(DFUSelectFileView.kt:47)
        at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1.onActivityResult(ActivityResultRegistry.kt:106)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:409)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:366)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:712)
        at android.app.Activity.dispatchActivityResult(Activity.java:8382)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5297)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5343)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by sylwester-zielinski** [comment]
Hello,

Thank you for reporting the issue.

I've checked the code and this exception is not a FATAL exception. Actually loading file has two scenarios.
First, a file has "file" scheme and can be directly opened, because operation happens in try catch block so an exception is printed.
If the file lacks "file" scheme then, in catch block, conentResolver is used to open the file.

So my question is: if the file was successfully loaded and displayed in UI? I will remove logging this exception as I can see it is a little confusing.

**Comment by MikeInMinnesota** [comment]
Yes, you are correct that it isn’t fatal to execution.  And you are also correct that there are 2 attempts, the first as a file and then in the catch block.  The first attempt fails and the 2nd attempt is what creates the exception.

No, the file isn’t successfully loaded.

The result of the exception and not loading isn’t really felt until later, when the zipfile object is used.  The DFU then fails at that point and the target device disconnects.

I believe the library is used in the nRF Toolbox on Android, because we also see the same DFU failure and disconnect behavior in the DFU utility.

Regards,
Mike

**Comment by philips77** [comment]
Hello @MikeInMinnesota,
Did you create the ZIP file with [*nrfutil*](https://github.com/NordicSemiconductor/pc-nrfutil)? Can you share it, or show what files are inside? Does it have *manifest.json* and a BIN and DAT file, or a pair of them, directly in the root, not in a subfolder?

**Comment by MikeInMinnesota** [comment]
Sure.  Attached is a representative .zip.  We use nrfutil for generating the file.  All the files are in the root.  We have successfully used this process for several years with the DFU utility in the Toolbox from both Android and IOS devices.  The target device is a nRF52840 running SDK 15.3 with a BLE bootloader.

The Android side is a Pixel 3XL that was updated to Android 12 last fall.  I don’t think it was used for updating since then, but I think it was able to update devices before that.

I don’t know if I mentioned this, but I was able to use this .zip to update devices through pc-nrfutil and a PCA10040 from a PC.

I’ll check and see what other phones I have laying around and see if they behave differently.

Regards,
Mike

**Comment by MikeInMinnesota** [comment]
I tried a Pixel XL with that .zip file and had no problems.  It’s Android 10 with DFU Library version 1.10.3.

Regards,
Mike

From: Michael D. Miller
Sent: Thursday, March 24, 2022 7:22 PM
To: NordicSemiconductor/Android-DFU-Library ***@***.***>
Subject: RE: [NordicSemiconductor/Android-DFU-Library] .zip fails on Android 12 (Issue #327)

Sure.  Attached is a representative .zip.  We use nrfutil for generating the file.  All the files are in the root.  We have successfully used this process for several years with the DFU utility in the Toolbox from both Android and IOS devices.  The target device is a nRF52840 running SDK 15.3 with a BLE bootloader.

The Android side is a Pixel 3XL that was updated to Android 12 last fall.  I don’t think it was used for updating since then, but I think it was able to update devices before that.

I don’t know if I mentioned this, but I was able to use this .zip to update devices through pc-nrfutil and a PCA10040 from a PC.

I’ll check and see what other phones I have laying around and see if they behave differently.

Regards,
Mike

**Comment by philips77** [comment]
Could you send us the ZIP at mag@nordicsemi.no? Seems like you were replying with an email and attachments don't seem to be supported on GitHub.

**Comment by sylwester-zielinski** [comment]
Hello Mike,

Thank you for sending the file.
Can you please send us en error code which is thrown? It would be the best if you can upload the whole logs.

**Comment by philips77** [comment]
Hello,
We're trying to understand what exactly is the issue that you're facing. The ZIP file that you've sent us "works". I mean it has been accepted by the library (and DFU app), and the DFU process started. Of course we did get INVALID OBJECT error, as we're testing with a debug key set, not yours, so our DK has rejected the init packet due to not matching signature, but that was expected.
We've tried it on Android 12.

**Comment by MikeInMinnesota** [comment]
Resending because original attachments were too large as .pdf format.

Regards,
Mike

From: Michael D. Miller
Sent: Monday, April 11, 2022 11:51 AM
To: NordicSemiconductor/Android-DFU-Library ***@***.***>; NordicSemiconductor/Android-DFU-Library ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [NordicSemiconductor/Android-DFU-Library] .zip fails on Android 12 (Issue #327)

Yes, I think you are correct about the file selection itself not being a problem.

Attached are two logs, one from an Android 10 unit that communicates successfully and one from an Android 12 unit that wasn’t able to communicate.

I haven’t looked in any detail except to note it looks like the Android 12 had an almost immediate disconnect from the GATT Server.

Regards,
Mike

**Comment by philips77** [comment]
The line printing this non-issue has been removed.
