### ISSUE TITLE
FW version failure, Error 11, Extended Error 5

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [NordicSemiconductor/Android-DFU-Library#395]
Hi @philips77, apologies for bothering you again, first of all, thank you for the help in https://github.com/NordicSemiconductor/Android-DFU-Library/issues/394, the updates work perfectly fine. 

Now, after finishing that implementation, my app's logic is to recursively check for additional updates, and if an update is found, then re-initiate the DFU process, so in my case, I have 3 pending updates, out of which, 2 recursive updates work absolutely fine, no issues there, but just with the last update, I'm facing an issue where the library throws the `FW version failure` error (more info in logs below). 

I tried going through a few other issues in this repo (like #124, #176, #327, etc) but none of those solutions seem to be viable in my case, that's why creating this issue.

According to your answer [here](https://github.com/NordicSemiconductor/Android-DFU-Library/issues/124#issuecomment-421979757), I can change the scope of the update to either target just BL+SD or just the App, so I tried it too. In my case, the hardware version stays the same, just the application version updates (but still I tried the system components scope as well just in case, logs below).

Adding logs below for the following cases:
1. Without using any scope
2. With Application scope (Constant: 2) only
3. With System Components scope (Constant: 1) only

## Without using any scope
```
I/DfuBaseService(13868): DFU service created. Version: 2.3.0
I/DfuBaseService(13868): Starting DFU service in foreground
I/DfuBaseService(13868): Connecting to the device...
D/BluetoothGatt(13868): connect() - device: C3:CE:FE:CF:F5:E9, auto: false
D/BluetoothGatt(13868): registerApp()
D/BluetoothGatt(13868): registerApp() - UUID=2fd8ea4e-ec2f-4996-8094-8380df2e0237
D/BluetoothGatt(13868): onClientRegistered() - status=0 clientIf=7
D/BluetoothGatt(13868): onClientConnectionState() - status=0 clientIf=7 device=C3:CE:FE:CF:F5:E9
I/DfuBaseService(13868): Connected to GATT server
I/DfuBaseService(13868): Waiting 1600 ms for a possible Service Changed indication...
D/BluetoothGatt(13868): onConnectionUpdated() - Device=C3:CE:FE:CF:F5:E9 interval=156 latency=0 timeout=400 status=0
D/BluetoothGatt(13868): discoverServices() - device: C3:CE:FE:CF:F5:E9
I/DfuBaseService(13868): Attempting to start service discovery... succeed
D/BluetoothGatt(13868): onConnectionUpdated() - Device=C3:CE:FE:CF:F5:E9 interval=156 latency=0 timeout=400 status=0
D/BluetoothGatt(13868): onSearchComplete() = Device=C3:CE:FE:CF:F5:E9 Status=0
I/DfuBaseService(13868): Services discovered
I/DfuImpl (13868): Buttonless service without bond sharing found -> SDK 13 or newer
W/DfuImpl (13868): Device is paired! Use Buttonless DFU with Bond Sharing instead (SDK 14 or newer)
I/DfuImpl (13868): Enabling indications...
D/BluetoothGatt(13868): setCharacteristicNotification() - uuid: 8ec90003-f315-4f60-9fb8-838830daea50 enable: true
I/flutter (13868): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13868): │ #0   ScannedBluetoothDevice.checkForDFU.<anonymous closure> (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:331:24)
I/flutter (13868): │ #1   NordicDfu.startDfu.<anonymous closure> (package:nordic_dfu/src/nordic_dfu.dart:137:32)
I/flutter (13868): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13868): │ 💡 DFU: onEnablingDfuMode called
I/flutter (13868): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/DfuImpl (13868): Sending Enter Bootloader (Op Code = 1)
I/DfuImpl (13868): Response received (Op Code = 1, Status = 1)
I/flutter (13868): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13868): │ #0   ScannedBluetoothDevice.checkForDFU.<anonymous closure> (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:338:24)
I/DfuBaseService(13868): Disconnecting from the device...
D/BluetoothGatt(13868): cancelOpen() - device: C3:CE:FE:CF:F5:E9
I/flutter (13868): │ #1   NordicDfu.startDfu.<anonymous closure> (package:nordic_dfu/src/nordic_dfu.dart:120:36)
I/flutter (13868): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13868): │ 💡 DFU: onDeviceDisconnecting called
I/flutter (13868): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/BluetoothGatt(13868): onClientConnectionState() - status=0 clientIf=7 device=C3:CE:FE:CF:F5:E9
I/DfuBaseService(13868): Disconnected from GATT server
I/DfuImpl (13868): Device disconnected
D/BluetoothGatt(13868): refresh() - device: C3:CE:FE:CF:F5:E9
I/DfuBaseService(13868): Refreshing result: true
I/DfuBaseService(13868): Cleaning up...
D/BluetoothGatt(13868): cancelOpen() - device: C3:CE:FE:CF:F5:E9
D/BluetoothGatt(13868): close()
D/BluetoothGatt(13868): unregisterApp() - mClientIf=7
I/DfuImpl (13868): Restarting to bootloader mode
D/BluetoothGatt(13868): onConnectionUpdated() - Device=C3:CE:FE:CF:F5:E9 interval=6 latency=0 timeout=500 status=0
D/BluetoothAdapter(13868): isLeEnabled(): ON
D/BluetoothLeScanner(13868): onScannerRegistered() - status=0 scannerId=4 mScannerId=0
D/BluetoothAdapter(13868): isLeEnabled(): ON
I/DfuImpl (13868): Scanning for new address finished with: C3:CE:FE:CF:F5:EA
I/DfuBaseService(13868): Starting DFU service in foreground
I/DfuBaseService(13868): Connecting to the device...
D/BluetoothGatt(13868): connect() - device: C3:CE:FE:CF:F5:EA, auto: false
D/BluetoothGatt(13868): registerApp()
D/BluetoothGatt(13868): registerApp() - UUID=ce7fe4ad-ca96-4fc9-ac59-1ba9c66807a2
D/BluetoothGatt(13868): onClientRegistered() - status=0 clientIf=7
D/BluetoothGatt(13868): onClientConnectionState() - status=0 clientIf=7 device=C3:CE:FE:CF:F5:EA
I/DfuBaseService(13868): Connected to GATT server
I/DfuBaseService(13868): Action received: android.bluetooth.device.action.ACL_CONNECTED
D/BluetoothGatt(13868): discoverServices() - device: C3:CE:FE:CF:F5:EA
I/DfuBaseService(13868): Attempting to start service discovery... succeed
D/BluetoothGatt(13868): onConnectionUpdated() - Device=C3:CE:FE:CF:F5:EA interval=12 latency=0 timeout=600 status=0
D/BluetoothGatt(13868): onConnectionUpdated() - Device=C3:CE:FE:CF:F5:EA interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(13868): onSearchComplete() = Device=C3:CE:FE:CF:F5:EA Status=0
I/DfuBaseService(13868): Services discovered
W/DfuImpl (13868): Secure DFU bootloader found
I/DfuImpl (13868): Requesting MTU = 517
D/BluetoothGatt(13868): configureMTU() - device: C3:CE:FE:CF:F5:EA mtu: 517
D/BluetoothGatt(13868): onConfigureMTU() - Device=C3:CE:FE:CF:F5:EA mtu=247 status=0
I/DfuImpl (13868): MTU changed to: 247
I/DfuImpl (13868): Enabling notifications...
D/BluetoothGatt(13868): setCharacteristicNotification() - uuid: 8ec90001-f315-4f60-9fb8-838830daea50 enable: true
I/DfuImpl (13868): Setting object to Command (Op Code = 6, Type = 1)
I/DfuImpl (13868): Command object info received (Max size = 512, Offset = 0, CRC = 00000000)
I/DfuImpl (13868): Sending the number of packets before notifications (Op Code = 2, Value = 0)
D/BluetoothGatt(13868): onConnectionUpdated() - Device=C3:CE:FE:CF:F5:EA interval=12 latency=0 timeout=600 status=0
I/DfuImpl (13868): Creating Init packet object (Op Code = 1, Type = 1, Size = 144)
I/DfuImpl (13868): Sending 144 bytes of init packet...
I/DfuImpl (13868): Sending init packet (Value = 12-8D-01-0A-47-08-01-12-43-08-EA-03-10-14-1A-04-83-02-CD-01-20-02-28-00-30-B0-96-02-38-00-42-24-08-03-12-20-7C-94-23-0A-68-99-27-84-97-56-FD-7E-70-AE-E3-1B-6D-0C-AC-AB-08-8D-31-D6-27-25-CC-F7-84-EA-CB-8B-48-00-52-04-08-01-12-00-10-00-1A-40-DD-D3-E7-E7-F0-87-72-EA-22-05-11-2B-4B-24-85-A4-FA-6F-D1-72-BE-BF-FB-12-C8-D6-1B-33-51-7B-C8-C4-18-D4-2A-C4-CF-25-22-1A-8C-49-59-25-BE-3E-71-CA-EF-06-A3-55-FC-8A-7A-BE-68-1F-4D-C2-BD-41-F3-E9)
I/DfuImpl (13868): Sending Calculate Checksum command (Op Code = 3)
I/DfuImpl (13868): Checksum received (Offset = 144, CRC = 14BF7BAA)
I/DfuImpl (13868): Executing init packet (Op Code = 4)
E/DfuImpl (13868): Executing object failed (error 11) (extended error 5): EXTENDED ERROR
E/DfuImpl (13868): Extended Error details: FW version failure
I/flutter (13868): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13868): │ #0   ScannedBluetoothDevice.checkForDFU.<anonymous closure> (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:338:24)
I/flutter (13868): │ #1   NordicDfu.startDfu.<anonymous closure> (package:nordic_dfu/src/nordic_dfu.dart:120:36)
I/flutter (13868): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13868): │ 💡 DFU: onDeviceDisconnecting called
I/flutter (13868): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/DfuBaseService(13868): Disconnecting from the device...
D/BluetoothGatt(13868): cancelOpen() - device: C3:CE:FE:CF:F5:EA
D/BluetoothGatt(13868): onClientConnectionState() - status=0 clientIf=7 device=C3:CE:FE:CF:F5:EA
I/DfuBaseService(13868): Disconnected from GATT server
D/BluetoothGatt(13868): refresh() - device: C3:CE:FE:CF:F5:EA
I/DfuBaseService(13868): Refreshing result: true
I/DfuBaseService(13868): Cleaning up...
D/BluetoothGatt(13868): cancelOpen() - device: C3:CE:FE:CF:F5:EA
D/BluetoothGatt(13868): close()
D/BluetoothGatt(13868): unregisterApp() - mClientIf=7
I/flutter (13868): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13868): │ 1029
I/flutter (13868): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13868): │ #0   ScannedBluetoothDevice.checkForDFU.<anonymous closure> (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:358:24)
I/flutter (13868): │ #1   NordicDfu.startDfu.<anonymous closure> (package:nordic_dfu/src/nordic_dfu.dart:145:22)
I/flutter (13868): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13868): │ ⛔ DFU: onError called. Error type: 3, Reason: FW version failure
I/flutter (13868): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13868): UpdateOnlyApp called!
I/DfuBaseService(13868): DFU service destroyed
E/flutter (13868): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(1029, DFU FAILED: FW version failure, Address: C3:CE:FE:CF:F5:EA, Error Type: 3, null)
E/flutter (13868): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (13868): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (13868): <asynchronous suspension>
E/flutter (13868): 
```

## With Application scope
```
I/DfuBaseService(23710): DFU service created. Version: 2.3.0
I/DfuBaseService(23710): Starting DFU service in foreground
D/CompatibilityChangeReporter(23710): Compat change id reported: 160794467; UID 10366; state: ENABLED
E/DfuBaseService(23710): An exception occurred while calculating file size
E/DfuBaseService(23710): java.io.IOException: Manifest file must specify at least one file.
E/DfuBaseService(23710): 	at no.nordicsemi.android.dfu.internal.ArchiveInputStream.<init>(ArchiveInputStream.java:215)
E/DfuBaseService(23710): 	at no.nordicsemi.android.dfu.DfuBaseService.openInputStream(DfuBaseService.java:1457)
E/DfuBaseService(23710): 	at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1201)
E/DfuBaseService(23710): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
E/DfuBaseService(23710): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/DfuBaseService(23710): 	at android.os.Looper.loopOnce(Looper.java:201)
E/DfuBaseService(23710): 	at android.os.Looper.loop(Looper.java:288)
E/DfuBaseService(23710): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (23710): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23710): │ 4098
I/flutter (23710): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23710): │ #0   ScannedBluetoothDevice.checkForDFU.<anonymous closure> (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:358:24)
I/flutter (23710): │ #1   NordicDfu.startDfu.<anonymous closure> (package:nordic_dfu/src/nordic_dfu.dart:145:22)
I/DfuBaseService(23710): DFU service destroyed
I/flutter (23710): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23710): │ ⛔ DFU: onError called. Error type: 0, Reason: DFU FILE ERROR
I/flutter (23710): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23710): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23710): │ #0   BabyBottles.observeDevicePreviews (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:429:14)
I/flutter (23710): │ #1   ScannedBluetoothDevice.checkForDFU.invalidateBottlesProvider (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:269:46)
I/flutter (23710): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23710): │ 💡 Observing device previews...
I/flutter (23710): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (23710): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(4098, DFU FAILED: DFU FILE ERROR, Address: C3:CE:FE:CF:F5:E9, Error Type: 0, null)
E/flutter (23710): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (23710): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (23710): <asynchronous suspension>
E/flutter (23710): 
```

In this case, the error says that the manifest file must specify at least one file and here is the manifest file retrieved from the API response:
```
manifest.json{
    "manifest": {
        "application": {
            "dat_file": "Production_App.dat", 
            "bin_file": "Production_App.bin", 
            "init_packet_data": {
                "application_version": 482, 
                "device_revision": 20
            }
        }
    }
}
```

## With System Components scope
```
I/DfuBaseService(27251): DFU service created. Version: 2.3.0
I/DfuBaseService(27251): Starting DFU service in foreground
D/CompatibilityChangeReporter(27251): Compat change id reported: 160794467; UID 10367; state: ENABLED
E/DfuBaseService(27251): An exception occurred while opening files. Did you set the firmware file?
E/DfuBaseService(27251): java.lang.NullPointerException
E/DfuBaseService(27251): 	at java.util.zip.CRC32.update(CRC32.java:71)
E/DfuBaseService(27251): 	at no.nordicsemi.android.dfu.internal.ArchiveInputStream.reset(ArchiveInputStream.java:462)
E/DfuBaseService(27251): 	at no.nordicsemi.android.dfu.internal.ArchiveInputStream.setContentType(ArchiveInputStream.java:558)
E/DfuBaseService(27251): 	at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1233)
E/DfuBaseService(27251): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
E/DfuBaseService(27251): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/DfuBaseService(27251): 	at android.os.Looper.loopOnce(Looper.java:201)
E/DfuBaseService(27251): 	at android.os.Looper.loop(Looper.java:288)
E/DfuBaseService(27251): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (27251): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (27251): │ 4098
I/flutter (27251): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (27251): │ #0   ScannedBluetoothDevice.checkForDFU.<anonymous closure> (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:358:24)
I/flutter (27251): │ #1   NordicDfu.startDfu.<anonymous closure> (package:nordic_dfu/src/nordic_dfu.dart:145:22)
I/flutter (27251): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (27251): │ ⛔ DFU: onError called. Error type: 0, Reason: DFU FILE ERROR
I/flutter (27251): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/DfuBaseService(27251): DFU service destroyed
I/flutter (27251): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (27251): │ #0   BabyBottles.observeDevicePreviews (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:429:14)
I/flutter (27251): │ #1   ScannedBluetoothDevice.checkForDFU.invalidateBottlesProvider (package:example_app_flutter/features/home/viewmodel/baby_bottle_providers.dart:269:46)
I/flutter (27251): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (27251): │ 💡 Observing device previews...
I/flutter (27251): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (27251): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(4098, DFU FAILED: DFU FILE ERROR, Address: C3:CE:FE:CF:F5:E9, Error Type: 0, null)
E/flutter (27251): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (27251): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (27251): <asynchronous suspension>
E/flutter (27251): 
```

In the nordic_dfu library, I can see that the zip file is always set first before setting any other configuration option(s), here's the [code](https://github.com/juliansteenbakker/nordic_dfu/blob/master/android/src/main/kotlin/dev/steenbakker/nordicdfu/NordicDfuPlugin.kt#L154).

**Comment by philips77** [comment]
You shouldn't need to use Scopes in this case.

This error seems to be expected. The bootloader verifies the new image based on the init packet. It contains the version of the new image. There is a default behavior, that the new bootlaoder has to have version number higher than the current one (if you're updating SD+BL or BL), and app needs to have at least the same version or higher. If the version number in the init packet is <= or < to the version currently running you'll get this error.

The version number you set in the `nrf util` command when you generate ZIP file.

**Comment by shubhamsinghmutualmobile** [comment]
> There is a default behavior

Is there no way to override this behavior?

**Comment by shubhamsinghmutualmobile** [comment]
If it is possible and not a deal breaker, would it please be possible to give a simple switch in the library (maybe named `Boolean forceUpdate`) that by default is `false` (thereby not affecting any of the existing users) and on `true`, overrides the behavior mentioned above?

**Comment by philips77** [comment]
I used `nrfutil pkg display <zipfile>` to list details of your init packet:
![Screenshot 2023-08-02 at 16 17 57](https://github.com/NordicSemiconductor/Android-DFU-Library/assets/6576580/20e1bc72-255b-4fc6-a06c-7d267a8e0a12)

It contains the bootloader, which means you need to recreate the zip with incremented version number to be able to update your device.

**Comment by shubhamsinghmutualmobile** [comment]
Understood. Thanks a lot, @philips77 

Just for my understanding, could you please explain to me what would happen if the version-checking logic was not there? Let's say someone flashes the same update twice, would that surely brick the device? Or there's a chance that the device might not be bricked but since Nordic had to cater to a much larger user base, it had to disable FW downgrade?

**Comment by shubhamsinghmutualmobile** [comment]
Understood. Much thanks for the explanation and for your time and effort. Closing this issue now :)
