### ISSUE TITLE
Android 12+ bug

### ISSUE THREAD

**Issue by dillanspencer** [NordicSemiconductor/Android-DFU-Library#399]
### DFU Bootloader version (please complete the following information):
 - nRF5 SDK version: 17
 - DFU Library version: 2.3.0

### Device information (please complete the following information):
 - Device: Samsung a14
 - OS: Android 13

### Your question
I get this error when trying to run a DFU

### Logs
```
FATAL EXCEPTION: IntentService[DfuBaseService]
Process: com.brnkl.app, PID: 17698
java.lang.IllegalArgumentException: com.brnkl.app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
	at android.app.PendingIntent.getActivity(PendingIntent.java:477)
	at android.app.PendingIntent.getActivity(PendingIntent.java:441)
	at no.nordicsemi.android.dfu.DfuBaseService.startForeground(DfuBaseService.java:1862)
	at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1142)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by dillanspencer** [comment]
Update to 1.12.0+ fixes this error. I get an error with android permissions after updating though
