### ISSUE TITLE
Firmware upgrade crashes on Android 8.1 because of the new way of the OS handling the notification

### ISSUE THREAD

**Issue by cnbuff410** [NordicSemiconductor/Android-DFU-Library#98]
Currently, all the firmware upgrade processes will crash on Android 8.1, and the crash report is:
```
 Error showing notification for service
 java.lang.RuntimeException: invalid channel for service notification: Notification(channel=dfu pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0xff888888 vis=PRIVATE)
 	at com.android.server.am.ServiceRecord$1.run(ServiceRecord.java:532)
 	at android.os.Handler.handleCallback(Handler.java:790)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:164)
 	at android.os.HandlerThread.run(HandlerThread.java:65)
 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
Shutting down VM
FATAL EXCEPTION: main
Process: com.stryd.pioneer, PID: 2071
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=dfu pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0xff888888 vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
I did a little bit search online, and I think this stackoverflow post gives the best summary of this bug:

https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1

I can confirm that this crash only happens on Android 8.1 OS. Tested on 7.0 and 7.1 without any issue.

Can we get this bug fixed soon? Otherwise it's preventing all of our Android 8.1 users to get the firmware update. Thanks!

**Comment by philips77** [comment]
Just call this https://github.com/NordicSemiconductor/Android-DFU-Library/blob/7c68625ebf60eaba7a791e8ce00898d63b8b6eef/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceInitiator.java#L588 method before starting dfu. We call it in our Application#onCreate method.
